---
title: Class Script
subtitle: "DANL 310: Data Visualization and Presentation"
author:
  - name: Byeong-Hak Choe
    affiliation: SUNY Geneseo
    
date: 2026-02-16

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 10
  fig-height: 6


format:
  html:
    code-fold: true
    toc: true
    toc-title: "Contents"
    toc-expand: 3
    number-sections: true
    code-tools: true
    highlight-style: atom-one
---

```{r setup}
#| include: false

library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)

theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x =
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y =
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```


```{r}
library(tidyverse)
flights <- nycflights13::flights
```


# summarize

```{r}
not_cancelled <- flights |> 
  filter(!is.na(dep_delay), !is.na(arr_delay))
```

```{r}
nrow(flights) - nrow(not_cancelled)
```


```{r}
delays_by_plane <- not_cancelled |> 
  group_by(tailnum) |> 
  summarize(
    mean_arr_delay = mean(arr_delay, na.rm = TRUE),
    n_flights = n()
  )
```

```{r}
ggplot(delays_by_plane, 
       aes(x = n_flights, 
           y = mean_arr_delay)) +
  geom_point(alpha = 1/10) +
  geom_smooth()
```


```{r}
delays_by_plane |> 
  filter(n_flights > 25) |> 
  ggplot(aes(x = n_flights, 
           y = mean_arr_delay)) +
  geom_point(alpha = 1/10) +
  geom_smooth() +
  geom_smooth(method = lm, color = "maroon")
```



```{r}
delays_by_plane |> 
  filter(n_flights > 25) |> 
  ggplot(aes(x = log(n_flights), 
           y = log(mean_arr_delay))) +
  geom_point(alpha = 1/10) +
  geom_smooth() +
  geom_smooth(method = lm, color = "maroon")
```


```{r}
not_cancelled |> 
  summarize(mean_arr_delay = mean(arr_delay, na.rm = TRUE),
            median_arr_delay = median(arr_delay, na.rm = TRUE),
            )
```


```{r}
not_cancelled |> 
  summarize(iqr_arr_delay = IQR(arr_delay, na.rm = TRUE),
            q25_arr_delay = quantile(arr_delay, 0.25, na.rm = TRUE),
    q75_arr_delay = quantile(arr_delay, 0.75, na.rm = TRUE),
            sd(arr_delay, na.rm = TRUE))


```



```{r}
not_cancelled |> 
  group_by(year, month, day) |> 
  summarize(
    earliest_dep = min(dep_time, na.rm = TRUE),
    latest_dep   = max(dep_time, na.rm = TRUE)
  )
```


```{r}
df <- not_cancelled |> 
  summarize(dep_time_range = list(range(dep_time, na.rm = TRUE)))
```



```{r}
not_cancelled |> 
  arrange(year, month, day, dep_time) |> 
  group_by(year, month, day) |> 
  summarize(
    first_dep = first(dep_time),
    last_dep  = last(dep_time)
  )
```


```{r}
not_cancelled |> 
  arrange(year, month, day, dep_time) |> 
  group_by(year, month, day) |> 
  summarize(second_dep = nth(dep_time, 2))
```

```{r}
not_cancelled |> 
  arrange(year, month, day, dep_time) |> 
  group_by(year, month, day) |> 
  summarize(second_dep = nth(dep_time, 1))
```

```{r}
not_cancelled |> 
  group_by(year, month, day) |> 
  summarize(
    avg_delay = mean(arr_delay, na.rm = TRUE),
    avg_pos_delay = mean(arr_delay[arr_delay > 0], na.rm = TRUE)
  )
```

```{r}
not_cancelled |> 
  group_by(year, month, day) |> 
  mutate(r = min_rank(desc(dep_time))) |> 
  filter(r %in% range(r))
```
```{r}
# Which destinations have the most carriers?
not_cancelled |> 
  group_by(dest) |> 
  summarize(n_carriers = n_distinct(carrier)) |> 
  arrange(desc(n_carriers))

# Counts by destination
not_cancelled |> 
  count(dest)
```


```{r}

# Counts by destination
not_cancelled |> 
  count(dest)

not_cancelled |> 
  group_by(dest) |> 
  summarize(n = n())

```


```{r}
ggplot(diamonds) +
  geom_histogram(aes(x = carat), binwidth = 0.5)

```

```{r}
diamonds |> 
  count(cut_width(carat, .5))
```


```{r}
# How many flights left before 5am?
not_cancelled |> 
  group_by(year, month, day) |> 
  summarize(n_early = sum(dep_time < 500, na.rm = TRUE))
```


```{r}
not_cancelled |> 
  filter(dep_time < 500) |> 
  group_by(year, month, day) |> 
  summarize(n_early = n())
```
```{r}
# What proportion of flights are delayed by more than an hour?
not_cancelled |> 
  group_by(year, month, day) |> 
  summarize(prop_over_60 = mean(arr_delay > 60, na.rm = TRUE)) |> 
  ungroup() |> 
  skim()
```

```{r}
daily <- flights |> group_by(year, month, day)
daily

per_day <- daily |> summarize(flights = n())
per_day

per_month <- per_day |> summarize(flights = sum(flights))
per_month

per_year <- per_month |> summarize(flights = sum(flights))

per_year
```



```{r}
daily

daily |> 
  ungroup() |>               # no longer grouped by date
  summarize(flights = n())   # all flights in the dataset
```
```{r}
not_cancelled |> 
  group_by(year, month, day) |> 
  filter(dense_rank(desc(arr_delay)) <= 10)

```


```{r}

not_cancelled |> 
  group_by(year, month, day) |> 
  filter(min_rank(desc(arr_delay)) <= 10)

```


```{r}
popular_dests <- flights |> 
  group_by(dest) |> 
  filter(n() > 17250)

popular_dests |> 
  distinct(dest)
```


```{r}
nrow(
  popular_dests |> 
  filter(arr_delay > 0)
)
```


```{r}
popular_dests |> 
  filter(arr_delay > 0) |> 
  group_by(year, month, day, dest) |> 
  mutate(prop_delay = arr_delay / sum(arr_delay, na.rm = TRUE)) |> 
  select(year:day, dest, arr_delay, prop_delay)
```


# Classwork 6
## Q1
Find all flights that

```{r}
# Had an arrival delay of two or more hours
flights |> 
  filter(arr_delay > 120)

# Flew to Houston (IAH or HOU)
flights |> 
  filter(dest == "IAH" | dest == "HOU")

flights |> 
  filter(dest %in% c("IAH", "HOU"))

# Were operated by United (UA), American (AA), or Delta (DL)
flights |> 
  filter(carrier %in% c("UA", "AA", "DL"))

# Departed in summer (July, August, and September)
flights |> 
  filter(month %in% c(7,8,9))

# Arrived more than two hours late, but didn’t leave late
flights |> 
  filter(arr_delay > 120,
         dep_delay <= 0)

# Were delayed by at least an hour for the depature, but reduced the delay over 30 minutes during flight
flights |> 
  filter(dep_delay >= 60,
         dep_delay - arr_delay  > 30) |> 
  select(dep_delay, arr_delay)

# Departed between midnight and 6am (inclusive)

flights |> 
  filter( dep_time >= 0 , dep_time <= 600 ) |> 
  arrange(dep_time)


flights |> 
  filter( (dep_time >= 0 & dep_time <= 600) | dep_time == 2400 ) |> 
  arrange(-dep_time)

```


## Q2

How could you use `arrange()` to sort all missing values to the start?

```{r}
flights |> 
  skimr::skim(dep_delay)

flights |> 
  arrange(dep_delay)

```

```{r}

flights |> 
  arrange( desc( is.na(dep_delay) ) )

```

## Q3

Brainstorm as many ways as possible to select `dep_time`, `dep_delay`, `arr_time`, and `arr_delay` from flights.



```{r}
flights |> 
  select(starts_with("dep"), starts_with("arr"))
```


## Q4
```{r}
flights |> 
  select(ends_with("_time"), ends_with("_delay"), -starts_with("sched"), -starts_with("air"))
```


