---
title: "Feb 24, 2025 - Class Script"
subtitle: "DANL 310: Introduction to Data Analytics"
author: 
  - name: Byeong-Hak Choe
date: 2025-02-24

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true
    number-sections: true
    code-fold: show       # https://quarto.org/docs/output-formats/html-code.html  
    code-tools: true      # https://quarto.org/docs/reference/cells/cells-jupyter.html
    highlight-style: atom-one # atom-one tango espresso
---

```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)
library(gapminder)
library(socviz) # textbook r package

# To set default ggplot theme
# theme_set(theme_fivethirtyeight() +
#           theme(strip.background = element_rect(fill="lightgray"),
#                 axis.title.x = 
#                   element_text(angle = 0,
#                                size = rel(1.33),
#                                margin = margin(10,0,0,0)),
#                 axis.title.y = 
#                   element_text(angle = 90,
#                                size = rel(1.33),
#                                margin = margin(0,10,0,0))
#                 )
          # ) # theme_minimal() becomes default
# scale_color_discrete <- function(...) scale_color_tableau(...)
# scale_fill_discrete <- function(...) scale_fill_tableau(...)
```

```{r}
library(tidyverse)
```


# CW 6
## Question 1

```{r}
#| fig-height: 12
gapminder <- gapminder::gapminder


gapminder |> 
  filter(year == 2007,
         continent != "Oceania") |> 
  ggplot(aes(x = lifeExp,
             y = fct_reorder(country, lifeExp))) +
  geom_point(color = '#0072B2') +
  geom_text(aes(label = lifeExp),
            hjust = -.2) +
  facet_wrap(~continent,
             scales = "free_y") +
  labs(x = "",
       y = "",
       title = "Life Expectancy in 2007") +
  theme_minimal() 
```

# Annotate

```{r}
p <- ggplot(data = organdata, 
            mapping = 
              aes(x = roads, 
                  y = donors))
p + geom_point() +
  annotate(geom = "text",
           x = 80,
           y = 30,
           label = "Here is my comment:\n this is an example")
```


```{r}
p <- ggplot(data = organdata, 
            mapping = 
              aes(x = roads, 
                  y = donors))
p + geom_point() +
  annotate(geom = "rect",
           xmin = 50, xmax = 110,
           ymin = 27, ymax = 33,
           fill = 'red',
           alpha = .3) +
  annotate(geom = "text",
           x = 80,
           y = 30,
           label = "Here is my comment:\n this is an example")
```


```{r}
p <- ggplot(mpg, aes(displ, hwy)) +
  geom_point(
    data = 
      filter(mpg, 
             manufacturer == "subaru"), 
    color = "orange", 
    size = 3) +
  geom_point() 

p
```





```{r}
p <- ggplot(mpg, aes(displ, hwy)) +
  geom_point(
    data = 
      filter(mpg, 
             manufacturer == "subaru"), 
    color = "orange", 
    size = 3) +
  geom_point() 

p  +
  annotate(geom = "point",
           x = 5.5,
           y = 40,
           color = "orange",
           alpha = .75,
           size = 3) +
  annotate(geom = "point",
           x = 5.5,
           y = 40) 
```


# CW 6
## Q2
```{r}
electricity <- read_csv(
  'https://bcdanl.github.io/data/electricity-usa-chn.csv')
```
### (a)
```{r}
library(hrbrthemes)
electricity |> 
  ggplot(aes(x = year,
             y = value,
             color = energy)) +
  geom_line(linewidth = 1.5) +
  facet_wrap(~iso3c) +
  labs(x = "year",
        y = "Electricity\n Generation\n (TWh)",
       color = "Energy") +
  scale_color_viridis_d(option = "B") +
  theme_ipsum() +
  theme(strip.background = element_rect(fill="lightgray"),
        axis.title.y = element_text(angle = 0),
        legend.position = "top")
  
```


### (b)

```{r}
electricity_new <- electricity |> 
  arrange(iso3c, year, energy) |> 
  group_by(iso3c, year) |> 
  mutate(tot = sum(value)) |> 
  mutate(perc = value / tot) |> 
  mutate(tot_perc = sum(perc))
```

```{r}
electricity_new <- electricity |> 
  arrange(iso3c, year, energy) |> 
  group_by(iso3c, year) |> 
  mutate(tot = sum(value),
         perc = value / tot,
         tot_perc = sum(perc)) 


electricity_new |> 
  ggplot(aes(x = year,
             y = perc,
             color = energy)) +
  geom_line(linewidth = 1.5) +
  facet_wrap(~iso3c) +
  labs(x = "year",
        y = "Percentage of\n Electricity\n Generation\n (TWh)",
       color = "Energy") +
  scale_color_viridis_d(option = "B") +
  theme_ipsum() +
  theme(strip.background = element_rect(fill="lightgray"),
        axis.title.y = element_text(angle = 0),
        legend.position = "top")

```



# Color Palette

```{r}
# install.pacakges("RColorBrewer")
library(RColorBrewer)
```



```{r}
p <- ggplot(data = organdata,
            mapping = 
              aes(x = roads, 
                  y = donors, 
                  color = world))

p + geom_point(size = 2,
               alpha = .5) +
  scale_color_brewer(palette = "Set1")
```




```{r}
p <- ggplot(data = organdata,
            mapping = 
              aes(x = roads, 
                  y = donors, 
                  color = world))

p + geom_point(size = 2,
               alpha = .5) +
  scale_color_brewer(palette = "Set2")
```


