---
title: Class Script
subtitle: "DANL 310: Data Visualization and Presentation"
author:
  - name: Byeong-Hak Choe
    affiliation: SUNY Geneseo
    
date: 2026-03-25

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 10
  fig-height: 6


format:
  html:
    code-fold: true
    toc: true
    toc-title: "Contents"
    toc-expand: 3
    number-sections: true
    code-tools: true
    highlight-style: atom-one
---

```{r setup}
#| include: false

library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)

# theme_set(theme_ipsum()+
#           theme(strip.background =element_rect(fill="lightgray"),
#                 axis.title.x =
#                   element_text(angle = 0,
#                                size = rel(1.33),
#                                margin = margin(10,0,0,0)),
#                 axis.title.y =
#                   element_text(angle = 90,
#                                size = rel(1.33),
#                                margin = margin(0,10,0,0))
#                 )
#           )
```


```{r}
organdata <- socviz::organdata
```

```{r}
by_country <- socviz::organdata |>
  group_by(consent_law, country) |>
  summarize(
    donors_mean = mean(donors, na.rm = TRUE),
    donors_sd = sd(donors, na.rm = TRUE),
    gdp_mean = mean(gdp, na.rm = TRUE),
    health_mean = mean(health, na.rm = TRUE),
    roads_mean = mean(roads, na.rm = TRUE),
    cerebvas_mean = mean(cerebvas, na.rm = TRUE)
  )
```


```{r}
by_country_if <- socviz::organdata |>
  group_by(consent_law, country) |>
  summarize_if(is.numeric, lst(mean, sd), na.rm = TRUE) |>
  ungroup()
```



```{r}
by_country_skim <- socviz::organdata |>
  group_by(consent_law, country) |>
  skimr::skim()
```


# geom_text

```{r}
p <- ggplot(
  data = by_country,
  mapping = aes(x = roads_mean, 
                y = donors_mean)
)

p +
  geom_point() +
  geom_text(aes(label = country))
```

```{r}

p +
  geom_point() +
  geom_text(aes(label = country),
            hjust = 0)
```


```{r}

p +
  geom_point() +
  geom_text(aes(label = country),
            hjust = 1)
```


```{r}

p +
  geom_point() +
  geom_text(aes(label = country),
            hjust = 0.5)
```
```{r}
p +
  geom_point() +
  geom_text(
    aes(label = country),
    hjust = 0,
    size = 3.5,
    # nudge_x = 50, # Using the same 
    #                 # unit on the 
    #                 # x-axis scale
    nudge_y = -1,
    check_overlap = TRUE
  )
```
```{r}
# install.packages("ggrepel")
library(ggrepel)
```

```{r}
elections_historic <- socviz::elections_historic


??socviz::elections_historic

p <- ggplot(
  socviz::elections_historic,
  aes(x = popular_pct, y = ec_pct, label = winner_label)
)

p_base <- p +
  geom_hline(yintercept = 0.5, 
             linewidth = 1.4, 
             color = "gray60") +
  geom_vline(xintercept = 0.5, 
             linewidth = 1.4, 
             color = "gray60") +
  geom_point()

p_base
```
```{r}
p_base +
  geom_text_repel()
```

```{r}
p_base +
  geom_text_repel(
    size = 3.8,
    box.padding = 0.5,
    max.overlaps = 20
  )
```

```{r}
p_title <- "Presidential Elections:\n Popular & Electoral College Margins"
p_subtitle <- "1824-2016"
p_caption <- "Data for 2016 are provisional."
x_label <- "Winner's share of Popular Vote"
y_label <- "Winner's share of\nElectoral College\nVotes"

p_elec <- p_base +
  geom_text_repel() +
  scale_x_percent() +
  scale_y_percent() +
  labs(
    x = x_label,
    y = y_label,
    title = p_title,
    subtitle = p_subtitle,
    caption = p_caption
  )

p_elec
```


# Classwork 9

```{r}
library(tidyverse)
library(ggrepel)
library(rmarkdown)
library(hrbrthemes)
library(ggthemes)

ev <- read_csv("https://bcdanl.github.io/data/electric_vehicles_WA.csv")

ev |> 
  paged_table()
```


## Q1

Top 10 counties by number of EVs
```{r}
top10_counties <- ev |> 
  count(county) |> 
  slice_max(n, n = 10,
            with_ties = T)

```


Top 10 makes by number of EVs
```{r}
top10_makers <- ev |> 
  count(make) |> 
  slice_max(n, n = 10,
            with_ties = T)

```


Average electric range for makes with at least 500 vehicles
```{r}
avg_electric_range <- ev |> 
  group_by(make) |> 
  summarize(n = n(),
            avg_range = mean(electric_range, na.rm = T),
            avg_range = round(avg_range, 2)) |> 
  filter(n >= 500) |> 
  arrange(-avg_range,-n) |> 
  rename(n_make = n)
```



## Q2

```{r}
avg_electric_range |> 
  ggplot(aes(x = n_make,
             y = avg_range,
             label = make)) +
  geom_point(alpha = .5) +
  geom_text() +
  theme_ipsum()
```

## Q3

```{r}
#| fig-height: 10
avg_electric_range |> 
  mutate(tesla = ifelse(make == "TESLA", T, F)) |> 
  ggplot(aes(x = n_make,
             y = avg_range,
             label = make)) +
  geom_point(alpha = .5) +
  geom_text(size = 7.5,
            hjust = 0,
            vjust = 1,
            nudge_x = 500,
            check_overlap = T,
            aes(color = tesla),
            show.legend = F) +
  scale_color_manual(values = c( "grey", "maroon"))
  theme_ipsum() 
```

## Q4
```{r}
avg_electric_range |> 
  mutate(tesla = ifelse(make == "TESLA", T, F)) |> 
  ggplot(aes(x = n_make,
             y = avg_range,
             label = make)) +
  geom_point(alpha = .5) +
  geom_text_repel(size = 7.5,
            aes(color = tesla),
            show.legend = F,
            max.overlaps = 15,
            box.padding = .5) +
  scale_color_manual(values = c( "grey", "maroon"))
  theme_ipsum() 
```

## Q5


```{r}
avg_electric_range |> 
  mutate(tesla = ifelse(make == "TESLA", T, F)) |> 
  ggplot(aes(x = n_make,
             y = avg_range,
             label = make)) +
  geom_point(alpha = .5) +
  geom_text_repel(size = 7.5,
            aes(color = tesla),
            show.legend = F,
            max.overlaps = 15,
            box.padding = .5) + 
  annotate(
    geom = "label",
    label = "Highest average range",
    x = 70000,
    y = 80
  ) +
  annotate(
    geom = "segment",
    x = 70000, xend = 17135,
    y = 84.90, yend = 84.90,
    color = "darkorange",
    linewidth = 0.7,
    arrow = arrow(length = 
                    unit(0.15, "in"))
  ) +
  annotate(
    geom = "rect",
    label = "Highest average range",
    xmin = 17135 * .8, xmax = 17135 * 1.2,
    ymin = 84.90 * .975, ymax = 92.5 * 1.02,
    fill = "darkorange",
    alpha = .5
  ) +
  
  scale_color_manual(values = c( "grey", "maroon"))
  theme_ipsum() 
  
  
  
```