---
title: Lecture 8
subtitle: "DANL 310: Introduction to Data Analytics"
author: 
  - name: Byeong-Hak Choe
date: 2025-02-17

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true
    number-sections: true
    code-fold: show       # https://quarto.org/docs/output-formats/html-code.html  
    code-tools: true      # https://quarto.org/docs/reference/cells/cells-jupyter.html
    highlight-style: atom-one # atom-one tango espresso
---

```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)
library(gapminder)
library(socviz) # textbook r package

# To set default ggplot theme
theme_set(theme_fivethirtyeight() +
          theme(strip.background = element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          ) # theme_minimal() becomes default
# scale_colour_discrete <- function(...) scale_color_tableau(...)
# scale_fill_discrete <- function(...) scale_fill_tableau(...)
```



# HW1
## Q7

```{r}
titanic <- read_csv(
  'https://bcdanl.github.io/data/titanic_cleaned.csv')
```

```{r}
titanic |> 
  ggplot(aes(x = age,
             y = after_stat(count))) +
  geom_density()
```


```{r}

titanic_female <- titanic |> 
  mutate(gender = "female",
         gender_new = "all passengers")

titanic_male <- titanic |> 
  mutate(gender = "male",
         gender_new = "all passengers")

titanic_2x <- titanic_male |> 
  rbind(titanic_female)


titanic <- titanic |> 
  mutate(gender_new = gender)


ggplot(data = titanic,
         aes(x = age,
             y = after_stat(count),
             fill = gender_new)) +
  geom_density(data = titanic_2x) +
  geom_density() +
  facet_wrap(~gender)
```

## Q3

```{r}
library(ggridges)
ncdc_temp <- read_csv(
  'https://bcdanl.github.io/data/ncdc_temp_cleaned.csv')

```

```{r}
ggplot(ncdc_temp,
       aes(x = temperature,
           y = factor(month))) +
  geom_density_ridges()
```


# CW 5
## Q2c

```{r}
organdata <- socviz::organdata

DT::datatable(organdata)
```

```{r}
by_country <- organdata |> 
  group_by(consent_law, country) |>
  summarize_if(is.numeric, lst(mean, sd), na.rm = TRUE) |>
  ungroup()
```

```{r}
by_country |> 
  ggplot(aes(x = donors_mean,
             y = fct_reorder(country, donors_mean),
             xmin = donors_mean - donors_sd,
             xmax = donors_mean + donors_sd)) +
  geom_pointrange() +
  labs(y = "",
       x = "Donor Procurement Rate")

```



# Scale

```{r}
p <- ggplot(data = organdata,
            mapping = aes(x = roads, y = donors, color = world))
p + geom_point()
```



```{r}
p <- ggplot(data = organdata,
            mapping = aes(x = roads, y = donors, color = world))
p + 
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous() +
    scale_color_manual(values = c('#009392', '#9ccb86', '#eeb479', '#cf597e'),
                       breaks = c("Liberal", "SocDem"))

  
  
```


```{r}
library(tidyverse)
library(ggthemes)
ggplot( data = mpg,
        mapping = 
          aes(x = displ,
              y = hwy, 
              color = class) ) + 
  geom_point(size = 3) 
```


```{r}
ggplot( data = mpg,
        mapping = 
          aes(x = displ,
              y = hwy, 
              color = class) ) + 
  geom_point(size = 3) +
  scale_color_colorblind()
```



```{r}
ggplot( data = mpg,
        mapping = 
          aes(x = displ,
              y = hwy, 
              color = class) ) + 
  geom_point(size = 3) +
  scale_color_tableau()
```



```{r}
ggplot( data = mpg,
        mapping = 
          aes(x = displ,
              y = hwy, 
              color = class) ) + 
  geom_point(size = 3) +
  scale_color_viridis_d()
```


# CW 5
## Q2d

```{r}
organdata |> 
  ggplot(aes(x = roads,
             y = donors,
             color = world)) +
  geom_point() +
  scale_color_tableau() +
  scale_y_continuous(breaks = c(5,15,25),
                     labels = c("Five", "Fifteen", "Twenty Five")) 
```


```{r}
organdata |> 
  ggplot(aes(x = roads,
             y = donors,
             color = world)) +
  geom_point() +
  scale_color_manual(labels = c("Corporatist", "Liberal", "SocDem", "Unclassfied"),
                     values = c("red", "green", "blue", "grey")) +
  labs(x = "... x",
       y = "... y",
       color = "... color")
```


```{r}

organdata |> 
  ggplot(aes(x = roads,
             y = donors,
             color = consent_law)) +
  geom_point(show.legend = F) +
  facet_wrap(~consent_law, ncol = 1) +
  scale_color_manual(values = c("steelblue", "darkorange"))
```

## Q2g

```{r}

organdata |> 
  ggplot(aes(x = roads,
             y = donors,
             color = consent_law)) +
  geom_point() +
  labs(title = "By Consent Law",
       x = "Road Death",
       y = "Donor Procurement",
       color = "Legal Regime: ") +
    scale_color_manual(values = c("steelblue", "darkorange")) +
  theme(plot.title = element_text(color = "brown",
                                  size = rel(2),
                                  hjust = .5),
        axis.title.x = element_text(color = "brown",
                                  size = rel(2),
                                  hjust = .5),
        axis.text.x = element_text(color = "blue",
                                  size = rel(2),
                                  hjust = .5,
                                  angle = 45),
        )

```




