---
title: Lecture 6
subtitle: "DANL 310: Introduction to Data Analytics"
author: 
  - name: Byeong-Hak Choe
date: 2025-02-10

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true
    number-sections: true
    code-fold: show       # https://quarto.org/docs/output-formats/html-code.html  
    code-tools: true      # https://quarto.org/docs/reference/cells/cells-jupyter.html
    highlight-style: atom-one # atom-one tango espresso
---

```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)
library(gapminder)

# To set default ggplot theme
theme_set( theme_fivethirtyeight() ) # theme_minimal() becomes default
```




# Show the right number
## Line chart

```{r}
ggplot(gapminder,
       aes(x = year,
           y = gdpPercap)) +
  geom_line()
```


```{r}
ggplot(gapminder,
       aes(x = year,
           y = gdpPercap)) +
  geom_line() +
  geom_point()
```



```{r}
ggplot(gapminder,
       aes(x = year,
           y = gdpPercap,
           group = country)) +
  geom_line()
```




```{r}
df <- gapminder |> 
  filter(country %in% c("United States",
                        "United Kingdom",
                        "China",
                        "Japan",
                        "Canada"))

df |> 
  ggplot(aes(x = year,
             y = gdpPercap,
             color = country)) +
  geom_point(color = "black") +
  geom_line()
```



```{r}
df <- gapminder |> 
  filter(country %in% c("United States",
                        "United Kingdom",
                        "China",
                        "Japan",
                        "Canada"))

df |> 
  ggplot(aes(x = year,
             y = log(gdpPercap),
             color = country)) +
  geom_point(color = "black") +
  geom_line() 
```


```{r}
gapminder <- gapminder
p <- ggplot(gapminder,
            aes(x = year,
                y = gdpPercap))

p +
  geom_line(aes(group = country)) +
  facet_wrap(~continent)
```

```{r}

p +
  geom_line(aes(group = country),
            color = "grey") +
  geom_smooth() +
  facet_wrap(~continent)
```

```{r}

p +
  geom_line(aes(group = country),
            color = "grey") +
  geom_smooth() +
  facet_wrap(~continent,
             nrow = 1) +
  scale_y_log10(labels = scales::dollar) +
  labs(x = "Year", 
       y = "GDP per capita",
       title = "GDP per capita on Five Continents") +
  theme(
    axis.text.x = element_text(
    angle = 45
  ),
    axis.title.x = element_text(margin = margin(50, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 50, 0, 0))
  )
```

```{r}
# install.packages("socviz")
library(socviz)
?gss_sm

gss_sm <- gss_sm
skimr::skim(gss_sm)

```

```{r}
p <- ggplot(gss_sm,
            aes(x = age,
                y = childs))

p +
  geom_point(alpha = .25) +
  geom_smooth()
```

```{r}
#| fig-height: 24
ggplot(gss_sm,
       aes(x = factor(childs) )) +
  geom_bar() +
  facet_wrap(~age)
```


- Boxplot
```{r}
ggplot(gss_sm,
            aes(x = age,
                y = factor(childs))) +
  geom_boxplot()
```

```{r}
#| fig-height: 18
p <- ggplot(data = gss_sm,
            mapping = 
              aes( x = age, 
                   y = childs ))

p + 
  geom_point(alpha = 0.2) +
  geom_smooth() +
  facet_grid( race + degree ~ sex,
              scales = "free_y")
```


# Bar

```{r}
gss_sm |> 
  count(bigregion)


ggplot(gss_sm,
       aes(x = bigregion)) +
  geom_bar()
```

- Proportional bar charts

```{r}
ggplot(gss_sm,
       aes(x = bigregion,
           y = ..prop..,
           group = 1)) +
  geom_bar() +
  labs(y = "Proportion") +
  theme_grey()
```



- groupby

```{r}
df <- gss_sm |> 
  group_by(religion)

df

```


```{r}
gss_sm |> 
  count()
```

```{r}
gss_sm |> 
  group_by(religion) |> 
  count()
```

```{r}
gss_sm |> 
  count(religion)
```



```{r}
p <- ggplot(data = gss_sm,
            mapping = 
              aes(x = religion, 
                  fill = religion))
p + 
  geom_bar(show.legend = F)
```



```{r}
p <- ggplot(data = gss_sm,
            mapping = 
              aes(x = bigregion, 
                  fill = religion))
p + 
  geom_bar(position = "fill")
```





```{r}
p <- ggplot(data = gss_sm,
            mapping = 
              aes(x = bigregion, 
                  fill = religion))
p + 
  geom_bar(position = "dodge2")
```





```{r}
p <- ggplot(data = gss_sm,
            mapping = 
              aes(x = bigregion, 
                  fill = religion))
p + 
  geom_bar(position = "dodge",
           mapping = 
             aes(y = ..prop..,
                 group = 1))
```



```{r}
p <- ggplot(data = gss_sm,
            mapping = 
              aes(x = bigregion, 
                  fill = religion))
p + 
  geom_bar(position = "dodge",
           mapping = 
             aes(y = ..prop..,
                 group = religion))
```



# Histogram, density plots

```{r}
midwest <- midwest
```


```{r}
ggplot(midwest,
       aes(x = area)) +
  geom_histogram()
```



```{r}
ggplot(midwest,
       aes(x = area)) +
  geom_histogram(bins = 50,
                 color = 'white',
                 fill = 'steelblue')
```

```{r}
p <- ggplot(data = 
              filter(midwest, 
                     state %in% 
                       c("OH", "WI")),
            mapping = 
              aes(x = percollege, 
                  fill = state) )
p + 
  geom_histogram(alpha = 0.4, 
                 bins = 20)
```



```{r}

p <- ggplot(data = 
              filter(midwest, 
                     state %in% 
                       c("OH", "WI")),
            mapping = 
              aes(x = percollege, 
                  fill = state) )
p + 
  geom_density(alpha = 0.4, 
                 )
```




```{r}
socviz::titanic
```

```{r}
oecd_sum
??oecd_sum
```


```{r}
oecd_sum |> 
  filter(!is.na(hi_lo)) |> 
  ggplot(aes(x = year,
           y = diff,
           fill = hi_lo)) +
  geom_col() +
   guides(fill = "none") +
  labs(x = NULL, 
       y = "Difference in Years",
       title = "The US Life Expectancy Gap",
       subtitle = "Difference between US and OECD
                   average life expectancies, 1960-2015",
       caption = "Data: OECD. After a chart by Christopher Ingraham,
                  Washington Post, December 27th 2017.") +
  theme_minimal()
```







