---
title: Class Script
subtitle: "DANL 310: Data Visualization and Presentation"
author:
  - name: Byeong-Hak Choe
    affiliation: SUNY Geneseo
    
date: 2026-03-04

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 10
  fig-height: 6


format:
  html:
    code-fold: true
    toc: true
    toc-title: "Contents"
    toc-expand: 3
    number-sections: true
    code-tools: true
    highlight-style: atom-one
---

```{r setup}
#| include: false

library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)

# theme_set(theme_ipsum()+
#           theme(strip.background =element_rect(fill="lightgray"),
#                 axis.title.x =
#                   element_text(angle = 0,
#                                size = rel(1.33),
#                                margin = margin(10,0,0,0)),
#                 axis.title.y =
#                   element_text(angle = 90,
#                                size = rel(1.33),
#                                margin = margin(0,10,0,0))
#                 )
#           )
```



```{r}
library(nycflights13)

flights |> 
  group_by(dest) |> 
  slice_head(n = 2) |> 
  relocate(dest)
```

```{r}
flights |> 
  group_by(dest) |> 
  slice_head(prop = 0.02) |> 
  relocate(dest)
```


```{r}
flights |> 
  group_by(dest) |> 
  slice_min(arr_delay, n = 1) |>
  relocate(dest, arr_delay)
```

```{r}

flights |> 
  group_by(dest) |> 
  slice_min(arr_delay, n = 1,
            with_ties = F) |>
  relocate(dest, arr_delay)
```


```{r}
flights |> 
  group_by(dest) |> 
  slice_max(arr_delay, n = 1) |>
  relocate(dest, arr_delay) |> 
  filter(n() > 1)
```
```{r}

flights |> 
  group_by(dest) |> 
  slice_max(arr_delay, n = 1,
            with_ties = F) |>
  relocate(dest, arr_delay)
```


## Tidy

```{r}
library(tidyverse)
table1
table2
table3

## Spread across two tibbles
table4a  ## cases
table4b
```


```{r}
table4a
```

```{r}
table4a |> 
  pivot_longer(cols = `1999`:`2000`,
               names_to = "year",
               values_to = "cases")
```

```{r}
table2
```

```{r}
table2 |> 
  pivot_wider(names_from = type,
              values_from = count)
```

```{r}
table2 |> 
  pivot_wider(names_from = type,
              values_from = count,
              names_prefix = "n_")

```


```{r}
table3
```

```{r}
table3 |> 
  separate(rate, into = c("cases", "pop"))
```


```{r}
table3 |> 
  separate(rate, into = c("cases", "population"), sep = "/")
```

```{r}
table3
```


```{r}
table3 |> 
  separate(year, into = c("century", "year"))
```


```{r}
table3 |> 
  separate(year, into = c("century", "year"), sep = 2)
```

```{r}
table5
```

```{r}
table5 |> 
  unite(new, century, year)
```


```{r}
table5 |> 
  unite(new, century, year, sep = "")

```


```{r}
library(nycflights13)
flights

flights <- flights
colnames(flights)
```

```{r}
airlines
```

```{r}
airports
```

```{r}

planes
```

```{r}

weather
```


```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3" )

y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3" )
```




```{r}
flights |> 
  left_join(weather)
  
```
```{r}
planes
```

```{r}
flights |> 
  left_join(planes)
```


```{r}
flights |> 
  left_join(planes, 
            by = "tailnum")
```


```{r}
flights |> 
  left_join(airports)
  
```

```{r}

flights |> 
  left_join(airports, 
            by = c("dest" = "faa"))
```



```{r}

flights |> 
  left_join(airports, 
            c("origin" = "faa"))
```



```{r}
x <- data.frame(
  a = c(1,2,3),
  b = c("a", "b", "c")
)


xx <- data.frame(
  a = c(1,2,3),
  c = c("a", "b", "c")
)


y <-  data.frame(
  a = c(4,5,6),
  b = c("d", "e", "f")
)
```



```{r}
xy <-rbind(x, y)
```

```{r}
xy_col <- cbind(x,y)
```

```{r}
xy <-bind_rows(x, y)
```

```{r}
xy_col <- bind_cols(x,y)
```

```{r}
rbind(x, xx)
```



```{r}
bind_rows(x, xx)
```
# Factor

```{r}
months <- c(
  "Jan", "Feb", "Mar", "Apr", 
  "May", "Jun", "Jul", "Aug", 
  "Sep", "Oct", "Nov", "Dec")
x1 <- 
  c("Dec", "Apr", "Jan", "Mar")
y1 <- factor(x1, 
             levels = months)
sort(y1)
```



```{r}
x2 <- 
  c("Dec", "Apr", "Jam", "Mar")

y2 <- factor(x2, 
             levels = months)
y2

factor(x1)
```




```{r}
x1
unique(x1)
f1 <- factor(x1, levels = unique(x1))
f1

levels(f1)
```

```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")

y3 <- 
  factor(x1,
         levels = c("Jan", "Apr", 
                    "Mar", "Dec"),
         labels = c("January", "April",
                    "March", "December"))
y3
```

```{r}
# labels are useful for recoding
x3 <- c(1, 2, 2, 1, 3)

y4 <- factor(x3,
             levels = c(1, 2, 3),
             labels = c("Low", 
                        "Medium", 
                        "High"))
y4
levels(y4)
```

```{r}

gss_cat <- forcats::gss_cat

class(gss_cat$race)

gss_cat |>
  count(race)
```

```{r}
relig_summary <- gss_cat |>
  group_by(relig) |>
  summarize(
    age = mean(age, na.rm = T),
    tvhours = mean(tvhours, na.rm = T),
    n = n()
  )
```



```{r}
ggplot(relig_summary, 
       aes(tvhours, relig)) + 
  geom_point()
```


```{r}
ggplot(relig_summary, 
       aes(tvhours, relig)) + 
  geom_bar(
    stat = "identity"
  )
```

```{r}
ggplot(relig_summary, 
       aes(tvhours, relig)) + 
  geom_col()
```


```{r}
ggplot(relig_summary, 
       aes(tvhours, 
           fct_reorder(relig, tvhours))) + 
  geom_col()
```

```{r}
by_age <- gss_cat |>
  filter(!is.na(age)) |>
  count(age, marital) |>
  group_by(age) |>
  mutate(prop = n / sum(n))

# Default legend order (alphabetical)
ggplot(by_age, aes(x = age, y = prop, color = marital)) +
  geom_line(linewidth = 1) +
  scale_color_brewer(palette = "Set1")

```

```{r}

# Legend order follows the line endings at the largest age
ggplot(by_age, aes(x = age, y = prop,
                   color = fct_reorder2(marital, age, prop))) +
  geom_line(linewidth = 1) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "marital")
```


