---
title: Class Script
subtitle: "DANL 310: Data Visualization and Presentation"
author:
  - name: Byeong-Hak Choe
    affiliation: SUNY Geneseo
    
date: 2026-02-09

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 10
  fig-height: 6


format:
  html:
    code-fold: true
    toc: true
    toc-title: "Contents"
    toc-expand: 3
    number-sections: true
    code-tools: true
    highlight-style: atom-one
---

```{r setup}
#| include: false

library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)

theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x =
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y =
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```



```{r}
custdata <- read_csv('https://bcdanl.github.io/data/custdata_rev.csv')
```

```{r}
class(custdata)
custdata$age
```



```{r}
col_names <- colnames(custdata)
```

```{r}
rownames(custdata)
```


```{r}
rownames(custdata) <- custdata$custid
```


```{r}
colnames(custdata) <- str_c("var_", colnames(custdata))
```


```{r}
skim(custdata)
```

```{r}
sum_custdata <- skim(custdata)
```


```{r}
custdata |> 
  skim()
```

```{r}
sum_group_cust <- custdata |> 
  group_by(var_state_of_res) |> 
  skim()
```


# Classwork 5

```{r}
# install.packages("ggthemes")
library(ggthemes)
library(tidyverse)

flights <- nycflights13::flights
```


## Question 1

```{r}
ggplot(data = flights,
       mapping = aes(x = air_time)) +
  geom_histogram(binwidth = 1)
```




## Question 2

### Part A
```{r}
ggplot(data = flights,
       mapping = aes(x = air_time)) +
  geom_histogram(bins = 50,
                   fill = "lightblue") +
  facet_wrap(~ origin)
```


### Part B
```{r}
ggplot(data = flights,
       mapping = aes(x = air_time,
                     color = origin,
                     fill = origin)) +
  geom_density(alpha = .25)
```


### Part C
```{r}
ggplot(data = flights,
       mapping = aes(x = air_time,
                     y = origin,
                     fill = origin,
                     )) +
  geom_boxplot(show.legend = FALSE)
```




## Question 3

```{r}
top3_n <- flights |> 
  count(carrier) |> 
  arrange( desc(n) ) |> 
  head(3)  # returns the first 3 observations in the given data.frame
```




## Question 4

```{r}

airlines <- nycflights13::airlines
top3_carriers <- flights |> 
  filter(carrier %in% c("UA", "B6", "EV")) |> 
  select(month, day, dep_time, carrier, origin, dest)
```




## Question 5

### Part A
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = carrier,
                     fill = carrier)) +
  geom_bar(show.legend = FALSE)
```


### Part B
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = carrier,
                     x = after_stat(prop),
                     group = 1)) +
  geom_bar(show.legend = FALSE)
```





## Question 6

### Part A
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = origin,
                     fill = carrier)) +
  geom_bar()
```


### Part B
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = origin,
                     fill = carrier)) +
  geom_bar(position = "fill") +
  labs(x = "Proportion") # label x-axis title
```

### Part C
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = origin,
                     fill = carrier)) +
  geom_bar(position = "dodge")
```
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = origin,
                     fill = carrier)) +
  geom_bar(position = "dodge2")
```
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = origin,
                     fill = carrier)) +
  geom_bar(position = position_dodge2())
```

### Part D
```{r}
ggplot(data = top3_carriers,
       mapping = aes(y = carrier,
                     fill = carrier)) +
  geom_bar(show.legend = FALSE) +
  facet_wrap( ~ origin)
```





## Question 7

```{r}
ggplot(data = top3_n,
       mapping = aes(x = n,
                     y = carrier,
                     fill = carrier)) +
  geom_col(show.legend = FALSE)
```



## Question 8

```{r}
ggplot(data = top3_n,
       mapping = aes(x = n,
                     y = fct_reorder(carrier, n))) +
  geom_col() +
  labs(y = "Carrier")   # label y-axis title
```
```{r}
ggplot(data = top3_n,
       mapping = aes(x = n,
                     y = fct_reorder(carrier, n))) +
  geom_col()
```


## Question 9

```{r}
carrier_per_origin <- flights |> 
  count(origin, carrier) |> 
  arrange(origin, -n)
```



# filter()

```{r}
# install.packages("nycflights13")  # Install once
library(nycflights13)
library(tidyverse)

flights <- nycflights13::flights

flights$month == 1  # A logical test returns TRUE or FALSE
class(flights$month == 12)  
```
```{r}
# Flights in January or December
jan <- flights |> 
  filter(month == 1)

dec <- flights |> 
  filter(month == 12)
```

```{r}
# Flights on January 1st or December 25th
jan1 <- flights |> 
  filter(month == 1, day == 1)

dec25 <- flights |> 
  filter(month == 12, day == 25)
```


```{r}
df <- data.frame(
  num = c(8, 9, 10, 11),
  chr = c("A", "C", "B", "A")
  )
```

```{r}
df |> 
  filter(num > 8)
```

```{r}
df |> 
  filter(chr == "A")
```

