---
title: Lecture 3
subtitle: "DANL 310: Introduction to Data Analytics"
author: 
  - name: Byeong-Hak Choe
date: 2025-01-27

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true
    number-sections: true
    code-fold: show       # https://quarto.org/docs/output-formats/html-code.html  
    code-tools: true      # https://quarto.org/docs/reference/cells/cells-jupyter.html
    highlight-style: atom-one # atom-one tango espresso
---

- Tips: Use shortcut to add a code chunk
  - Alt + Ctrl + I 
  - option + command + I 

```{r}
library(gapminder)
gapminder <- gapminder::gapminder
```

```{r}
# install.packages("skimr")
library(skimr)
skim(gapminder)
```


```{r}
library(tidyverse)
p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))

p + geom_point()
```


```{r}
p + geom_point() + geom_smooth()

```



```{r}
p + geom_point() + geom_smooth(method = lm)

```


```{r}
p + 
  geom_point() + 
  geom_smooth(method = lm)

```

```{r}
p1 <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp,
                          color = continent))

```

```{r}
p1 + geom_point()
```

```{r}
p1 + 
  geom_point() +
  geom_smooth()
```


```{r}

p2 <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp))

p2 +
  geom_point(color = "purple") +
  geom_smooth(color = "orange")
```



```{r}

p2 +
  geom_point(color = "purple") +
  geom_smooth(color = "orange", 
              se = F, 
              size = 8, 
              method = "lm") 
```




```{r}
p + geom_point(alpha = 0.3) +
    geom_smooth(method = "gam") +
    scale_x_log10(labels = scales::dollar) +
    labs(x = "GDP Per Capita", 
         y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")
```


```{r}
p <- ggplot(data = gapminder, 
            mapping = aes(x = gdpPercap, y = lifeExp))

p + geom_point(mapping = aes(color = continent)) +
    geom_smooth(method = "loess")  +
    scale_x_continuous(trans = scales::log_trans())  # natural log
```


